-- AlterTable
ALTER TABLE `menu` ADD COLUMN `canCreate` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `canDelete` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `canUpdate` BOOLEAN NOT NULL DEFAULT false;
