-- CreateTable
CREATE TABLE `Menu` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `menuId` VARCHAR(191) NOT NULL,
  `title` VARCHAR(191) NOT NULL,
  `href` VARCHAR(191) NOT NULL,
  `icon` VARCHAR(191) NOT NULL,
  `order` INTEGER NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  PRIMARY KEY (`id`),
  UNIQUE INDEX `Menu_menuId_key`(`menuId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
